require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.telescope")
require("user.gitsigns")
require("user.nvim-tree")
-- require("user.neo-tree")
require("user.bufferline")
--require("user.feline")
require("user.autopairs")
require("user.comment")
require("colorizer").setup() -- further config https://github.com/norcalli/nvim-colorizer.lua
